# Generated by Django 2.2 on 2019-05-15 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190515_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete='', to=settings.AUTH_USER_MODEL),
        ),
    ]
